export default profesores_categorias_list = [
    "Nivel inicial - Ambiente natural, social y tecnológico", 
    "Nivel inicial - Educación física",
    "Nivel inicial - Expresión artística",
    "Nivel inicial - Formación personal y social",
    "Nivel inicial - Juegos",
    "Nivel inicial - Matemática",
    "Nivel inicial - Prácticas del lenguaje",
    "Educación Primaria - Arte",
    "Educación Primaria - Ciencias naturales",
    "Educación Primaria - Ciencias sociales",
    "Educación Primaria - Educación física",
    "Educación Primaria - Educación sexual integral",
    "Educación Primaria - Formación ética y ciudadana",
    "Educación Primaria - Lengua",
    "Educación Primaria - Lenguas extranjeras",
    "Educación Primaria - Matemática",
    "Educación Primaria - Tecnología",
    "Educación Secundaria - Artes",
    "Educación Secundaria - Ciencias agrarias y ambiente",
    "Educación Secundaria - Ciencias ambientales",
    "Educación Secundaria - Ciencias naturales",
    "Educación Secundaria - Ciencias sociales",
    "Educación Secundaria - Comunicación",
    "Educación Secundaria - Economía y administración",
    "Educación Secundaria - Educación física",
    "Educación Secundaria - Educación sexual integral",
    "Educación Secundaria - Filosofía",
    "Educación Secundaria - Formación ética y ciudadana",
    "Educación Secundaria - Informática",
    "Educación Secundaria - Lengua",
    "Educación Secundaria - Lenguas extanjeras",
    "Educación Secundaria - Literatura",
    "Educación Secundaria - Matemática",
    "Educación Secundaria - Psicología",
    "Educación Secundaria - Tecnología",
    "Educación Secundaria - Turismo",
    "Terciario - Especificar en Observaciones",
    "Universitario - Especificar en Observaciones"
];